depression:
  - sad
  - sadness
  - hopelessness
  - hopeless
  - empty
  - emptiness
  - despair
  - guilty
  - guilt
  - loneliness
  - lonely
  - fatigue
  - insomnia
  - apathy
  - irritable
  - withdrawal
  - numbness
  - numb
  - worthless
  - failure
  - burden
  - regret
  - shame
  - self-doubt
  - therapy
  - medication
  - isolation
  - rumination
  - overthinking
  - avoidance
  - suicidal